SLACK_CHANNEL_NAME: "build-status"
ENVIRONMENT: "prod"
CODE_BASE_PATH: "env/prod"
ACTION_MESSAGE: "Starting Ansible Deployment"
KEEP_APPROVAL_STAGE: true

GIT_REPO_URL: "https://github.com/OT-MyGurukulam/Ansible_33.git"
GIT_BRANCH: "main"

ANSIBLE_PLAYBOOK: "site.yml"
ANSIBLE_INVENTORY: "inventory/prod"
